#!/bin/bash

########################################################################
# conda package lists
########################################################################

CONDA_PACKAGES=(
    autoconf
    automake
    bash
    bash-completion
    bison
    c-compiler
    cmake
    coreutils
    ctags
    curl
    findutils
    flex
    gawk
    git
    git-subrepo
    htop
    hunspell
    hunspell-en
    imagemagick
    ipython
    libtool
    make
    nodejs
    python
    requests
    tar
    tmux
    tree
    vim
    wget
    which
)

SAGE_PACKAGES=(
    jupyterlab
    sage
)

SAGE_PIPS=(
    sjk
)

JUPYTER_PACKAGES=(
    4ti2
    gap
    jupyterlab
    matplotlib
    normaliz
    numpy
    octave
    r
    scipy
    singular
    sympy
)

JUPYTER_PIPS=(
    sjk
)

DEV_PACKAGES=(
    qt
    mupdf
    pyqt
)

DEV_LOCAL_PACKAGES=(
    djvulibre
)

DEV_PIPS=(
    PyMuPDF
    python-djvulibre
)

########################################################################
# conda base
########################################################################

CONDA_BASE=$HOME/opt/miniconda3

########################################################################
# show_help
########################################################################

show_help() {

    UNAME_KERNEL=$(uname)
    DOTFILES_DIR_NAME=$(dirname "$(true_path "$0")")

    box_start "DOTFILES"
    box_row 16 35 \
        "./setup dotfiles" "  ::  setup configuration files in \$HOME"
    box_row 16 35 \
        "./setup conda"    "  ::  download and install miniconda3"
    box_row 16 35 \
        "./setup jupyter"  "  ::  setup jupyter environment in conda"
    box_row 16 35 \
        "./setup sage"     "  ::  setup sage environment in conda"
    [ "X$UNAME_KERNEL" = "XDarwin" ] && \
    box_row 16 35 \
        "./setup dev"      "  ::  setup dev environment in conda"
    [ "X$UNAME_KERNEL" = "XDarwin" ] && \
    box_row 16 35 \
        "./setup killdev"  "  ::  remove dev environment in conda"
    [ "X$UNAME_KERNEL" = "XDarwin" ] && \
    box_row 16 35 \
        "./setup djvu"     "  ::  build djvulibre library"
    [ -d "$DOTFILES_DIR_NAME/services/ngrok" ] && \
    box_row 16 35 \
        "./setup ngrok"    "  ::  setup ngrok service"
    [ -d "$DOTFILES_DIR_NAME/services/lab" ] && \
    box_row 16 35 \
        "./setup lab"      "  ::  setup jupyter lab service"
    box_row 16 35 \
        "./setup help"     "  ::  print this help"
    box_end

}

########################################################################
# box drawing
########################################################################

box_start() {
    TITLE=$1 
    if [ -n "$2" ]; then
        BOX_COLOR=$2
    else
        BOX_COLOR=34
    fi
    if [ -z "$NOT_FIRST_BOX" ]; then
        printf '\n'
        NOT_FIRST_BOX=true
    fi
    printf '  \033[00;%sm┌─── %s ' "$BOX_COLOR" "$TITLE"
    i=0
    padlen=$(( 74 - ${#TITLE} ))
    while [ "$i" -lt "$padlen" ]; do
        printf '─'
        i=$(( i+1 ))
    done
    printf '┐\033[00m\n'
    printf '  \033[00;%sm│%-79.79s│\033[00m\n' "$BOX_COLOR" ''
}

box_row() {
    CWIDTH1=$1
    COLOR=$2
    COL1=$3
    COL2=$4
    CWIDTH2=$(( 75 - CWIDTH1 ))
    printf '  \033[00;%sm│\033[00m  ' "$BOX_COLOR"
    printf '\033[00;%sm' "$COLOR"
    printf '%-*.*s' "$CWIDTH1" "$CWIDTH1" "$COL1"
    printf '\033[00m '
    printf '%-*.*s' "$CWIDTH2" "$CWIDTH2" "$COL2"
    printf ' \033[00;%sm│\033[00m\n' "$BOX_COLOR"
}

box_end() {
    printf '  \033[00;%sm│%-79.79s│\033[00m\n' "$BOX_COLOR" ''
    printf '  \033[00;%sm└' "$BOX_COLOR"
    i=0
    while [ "$i" -lt 79 ]; do
        printf '─'
        i=$(( i+1 ))
    done
    printf '┘\033[00m\n\n'
}

########################################################################
# setup_dotfiles
########################################################################

setup_dotfiles() {

    DOTFILES_DIR_NAME=$(dirname "$(true_path "$0")")

    UNAME=$(uname)

    if ! cd "$DOTFILES_DIR_NAME/configs"; then
        echo "Error. Cannot cd to \`$DOTFILES_DIR_NAME/configs\`"
        return 1
    fi

    box_start "DOTFILES SETUP"

    for DOTFILE in *; do
        case "$DOTFILE" in
            *[_@]mac)
                [ "X$UNAME" = "XDarwin" ] && link_dotfile "$DOTFILE" ;;
            *[_@]linux)
                [ "X$UNAME" = "XLinux" ] && link_dotfile "$DOTFILE" ;;
            *)
                link_dotfile "$DOTFILE" ;;
        esac
    done

    box_end

}

########################################################################
# link_dotfile
########################################################################

link_dotfile() {


    SOURCE_FILE=$DOTFILES_DIR_NAME/configs/$1

    LINK_FILE=$HOME/.${1%@*}

    if [ ! -e "$SOURCE_FILE" ]; then
        box_row 20 31 "$1" "source does not exist"
        return
    fi

    if [ -e "$LINK_FILE" ]; then

        if [ -L "$LINK_FILE" ]; then
            if [ "X$(true_path "$LINK_FILE")" = "X$SOURCE_FILE" ]; then
                box_row 20 39 "$1" "link was already configured"
                return
            fi
        fi

        backup_away "$LINK_FILE"
        MSG="targed existed, backup created, and "

    else

        MSG="new "

    fi

    ln -s "$SOURCE_FILE" "$LINK_FILE"
    box_row 20 32 "$1" "${MSG}link configured"

}

########################################################################
# true_path
########################################################################

true_path() {(
    ORIGINAL_FILE=$1
    TARGET_FILE=$1

    if ! cd "$(dirname "$TARGET_FILE")"; then
        echo "$ORIGINAL_FILE"
        return 1
    fi
    TARGET_FILE=$(basename "$TARGET_FILE")

    # Iterate down a (possible) chain of symlinks
    while [ -L "$TARGET_FILE" ]; do
        TARGET_FILE=$(readlink "$TARGET_FILE")
        if ! cd "$(dirname "$TARGET_FILE")"; then
            echo "$ORIGINAL_FILE"
            return 1
        fi
        TARGET_FILE=$(basename "$TARGET_FILE")
    done

    # Compute the canonicalized name by finding the physical path 
    # for the directory we're in and appending the target file.
    PHYS_DIR=$(pwd -P)
    RESULT=$PHYS_DIR/$TARGET_FILE
    echo "$RESULT"
)}

########################################################################
# backup_away
########################################################################

backup_away() {
    FILE=$1
    BACKUP_FILE=${FILE}_$(date '+%Y-%m-%d--%H-%M-%S')
    while [ -e "$BACKUP_FILE" ]; do
        sleep 1
        BACKUP_FILE=${FILE}_$(date '+%Y-%m-%d--%H-%M-%S')
    done
    mv "$FILE" "$BACKUP_FILE"
}

########################################################################
# setup_conda
########################################################################

setup_conda() {

    box_start "CONDA SETUP"

    if [ -e "$CONDA_BASE" ]; then
        box_row 1 31 "!" "Conda already setup (this script only needs to be run once)"
        box_end
        return
    fi

    box_row 1 33 "*" "Determining platform"

    UNAME_KERNEL=$(uname)
    UNAME_MACHINE=$(uname -m)
    if [ "X$UNAME_KERNEL" = "XDarwin" ]; then
        REPO=https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
    elif [ "X$UNAME_KERNEL" = "XLinux" ] && [ "X$UNAME_MACHINE" = "Xx86_64" ]; then
        REPO=https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    elif [ "X$UNAME_KERNEL" = "XLinux" ] && [ "X$UNAME_MACHINE" = "Xx86_64" ]; then
        REPO=https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86.sh
    else
        box_row 7 31 "* Error" "Platform not supported"
        box_end
        return
    fi

    box_row 1 33 "*" "Creating temporary directory"

    TEMPDIR=$(mktemp -d -t "dotfiles-XXXXXXXXXXXXXXXX")

    if ! cd "$TEMPDIR"; then
        box_row 7 31 "* Error" "Cannot cd to $TEMPDIR"
        box_end
        rm -rf "$TEMPDIR"
        return
    fi

    box_row 1 33 "*" "Downloading: $(basename "$REPO")"
    box_end

    curl -o miniconda_installer.sh "$REPO"

    printf '\n'

    box_start "CONTINUING CONDA SETUP"
    box_row 1 33 "*" "Installing miniconda"
    box_end

    bash ./miniconda_installer.sh -b -p "$CONDA_BASE"

    printf '\n'

    box_start "CONTINUING CONDA SETUP"
    box_row 1 33 "*" "Loading and activating conda"

    # shellcheck disable=SC1090
    . "$CONDA_BASE/etc/profile.d/conda.sh"
    conda activate base

    box_row 1 33 "*" "Configuring conda-forge"

    conda config --add channels conda-forge 2>/dev/null
    conda config --set channel_priority strict 2>/dev/null

    box_row 1 33 "*" "Configuring base environment"
    box_end

    conda install --name base conda-build mamba

    printf '\n'

    box_start "CONTINUING CONDA SETUP"
    box_row 1 33 "*" "Creating conda environment \`env0\`"
    box_end

    mamba create --name env0 "${CONDA_PACKAGES[@]}"

    printf '\n'

    box_start "CONTINUING CONDA SETUP"
    box_row 1 33 "*" "Cleaning temporary directory"

    rm -rf "$TEMPDIR"

    box_row 1 33 "*" "Done!"
    box_end

}

########################################################################
# check if conda is available
########################################################################

conda_exists() {
    conda >/dev/null 2>&1
}

########################################################################
# get conda environment list
########################################################################

conda_envs() {(
    IFS=$'\n' read -d '' -r -a LINES <<<"$(conda env list)"
    for LINE in "${LINES[@]}"; do
        read -r -a WORDS <<< "$LINE"
        word="${WORDS[0]}"
        if [ "X$word" != "X#" ]; then
            echo "$word"
        fi
    done
)}

########################################################################
# check if conda environment exists
########################################################################

conda_env_exists() {
    ENV_NAME="$1"
    for ENV in $(conda_envs); do
        if [ "X$ENV" = "X$ENV_NAME" ]; then
            return 0
        fi
    done
    return 1
}

########################################################################
# setup_conda_env
########################################################################

setup_conda_env() {

    local BOX_TITLE="$1"
    shift
    local ENV_NAME="$1"
    shift
    local ENV_PACKAGES="$1"
    shift
    local ENV_PIPS="$1"
    shift
    local ENV_LOCAL_PACKAGES="$1"

    box_start "$BOX_TITLE SETUP"
    box_row 1 33 "*" "Checking current setup"

    if ! conda_exists; then
        box_row 1 31 "!" "Conda not setup (please install conda first)"
        box_end
        return
    fi

    if conda_env_exists "$ENV_NAME"; then
        box_row 1 31 "!" "Conda environment \`$ENV_NAME\` already exists"
        box_end
        return
    fi

    box_row 1 33 "*" "Loading and activating conda"

    # shellcheck disable=SC1090
    . "$CONDA_BASE/etc/profile.d/conda.sh"
    conda activate base

    box_row 1 33 "*" "Creating and activating conda environment \`$ENV_NAME\`"
    box_end

    mamba create --name "$ENV_NAME" "${CONDA_PACKAGES[@]}" $ENV_PACKAGES


    if [ "$ENV_LOCAL_PACKAGES" ]; then

        conda activate "$ENV_NAME"

        box_start "CONTINUING $BOX_TITLE SETUP"
        box_row 1 33 "*" "Installing extra packages via pip"
        box_end

        mamba install --name "$ENV_NAME" --channel local $ENV_LOCAL_PACKAGES

    fi

    if [ "$ENV_PIPS" ]; then

        conda activate "$ENV_NAME"

        box_start "CONTINUING $BOX_TITLE SETUP"
        box_row 1 33 "*" "Installing extra packages via pip"
        box_end

        pip install $ENV_PIPS

    fi

    printf '\n'

    box_start "CONTINUING $BOX_TITLE SETUP"
    box_row 1 33 "*" "Done!"
    box_end

}

########################################################################
# setup_jupyter
########################################################################

setup_jupyter() {
    setup_conda_env \
        "JUPYTER" \
        "env-jupyter" \
        "${JUPYTER_PACKAGES[*]}" \
        "${JUPYTER_PIPS[*]}"
}

########################################################################
# setup_sage
########################################################################

setup_sage() {
    setup_conda_env \
        "SAGE" \
        "env-sage" \
        "${SAGE_PACKAGES[*]}" \
        "${SAGE_PIPS[*]}"
}

########################################################################
# setup_dev
########################################################################

setup_dev() {
    setup_conda_env \
        "DEV" \
        "env-dev" \
        "${DEV_PACKAGES[*]}" \
        "${DEV_PIPS[*]}" \
        "${DEV_LOCAL_PACKAGES[*]}"
}

########################################################################
# remove_dev
########################################################################

remove_dev() {
    box_start "REMOVING DEV ENVIRONMENT"
    box_row 1 33 "*" "Checking current setup"

    if ! conda_exists; then
        box_row 1 31 "!" "Conda not setup (please install conda first)"
        box_end
        return
    fi

    if ! conda_env_exists "env-dev"; then
        box_row 1 31 "!" "Conda environment \`env-dev\` does not exist"
        box_end
        return
    fi

    box_row 1 33 "*" "Loading and activating conda"

    # shellcheck disable=SC1090
    . "$CONDA_BASE/etc/profile.d/conda.sh"
    conda activate base

    box_row 1 33 "*" "Removing conda environment \`env-dev\`"
    box_end

    conda remove --name "env-dev" --all

    printf '\n'

    box_start "CONTINUING - REMOVING DEV ENVIRONMENT"
    box_row 1 33 "*" "Done!"
    box_end
}

########################################################################
# build_djvu
########################################################################

build_djvu() {
    box_start "BUILDING DJVULIBRE"
    box_row 1 33 "*" "Checking current setup"

    if ! conda_exists; then
        box_row 1 31 "!" "Conda not setup (please install conda first)"
        box_end
        return
    fi

    box_row 1 33 "*" "Loading and activating conda"

    # shellcheck disable=SC1090
    . "$CONDA_BASE/etc/profile.d/conda.sh"
    conda activate base

    box_row 1 33 "*" "Changing diretory"

    DOTFILES_DIR_NAME=$(dirname "$(true_path "$0")")
    RECIPES_DIR_NAME=$DOTFILES_DIR_NAME/conda_recipes

    cd "$RECIPES_DIR_NAME"

    box_row 1 33 "*" "Building package"
    box_end

    conda build djvulibre

    printf '\n'

    box_start "CONTINUING - BUILDING DJVULIBRE"
    box_row 1 33 "*" "Done!"
    box_end
}

########################################################################
# setup_ngrok
########################################################################

setup_service() {

    SERVICE_NAME="$1"

    DOTFILES_DIR_NAME=$(dirname "$(true_path "$0")")
    SRC_SERVICE_DIR=$DOTFILES_DIR_NAME/services/$SERVICE_NAME
    SRC_SERVICE_FILE=$SRC_SERVICE_DIR/$SERVICE_NAME.service
    OBJ_SERVICE_DIR=$HOME/.config/systemd/user/
    OBJ_SERVICE_FILE=$OBJ_SERVICE_DIR/$SERVICE_NAME.service

    box_start "$SERVICE_NAME.service SETUP"

    box_row 1 33 "*" "Checking if user '$USER' can run systemd services"

    if [ ! -e "/var/lib/systemd/linger/$USER" ]; then
        loginctl enable-linger "$USER"
    fi

    if [ ! -e "/var/lib/systemd/linger/$USER" ]; then
        box_row 1 31 "!" "User '$USER' cannot run systemd services"
        box_end
        return
    fi

    box_row 1 33 "*" "Checking files"

    if [ -e "$OBJ_SERVICE_FILE" ]; then
        box_row 1 31 "!" "'$SERVICE_NAME.service' already configured"
        box_end
        return
    fi

    if [ ! -e "$SRC_SERVICE_FILE" ]; then
        box_row 1 31 "!" "Source service file '$SERVICE_NAME.service' not found"
        box_end
        return
    fi

    box_row 1 33 "*" "Linking service file"

    box_end

    mkdir -p "$OBJ_SERVICE_DIR"

    ln -s "$SRC_SERVICE_FILE" "$OBJ_SERVICE_FILE"

    echo

    box_start "$SERVICE_NAME.service SETUP (CONTINUING)"

    box_row 1 33 "*" "Reloading systemd daemon list"

    systemctl --user daemon-reload

    box_row 1 33 "*" "Enabling service"

    box_end

    systemctl --user enable "$SERVICE_NAME.service"
    echo

    box_start "$SERVICE_NAME.service SETUP (CONTINUING)"

    box_row 1 33 "*" "Starting service"

    systemctl --user start "$SERVICE_NAME.service"

    box_row 1 33 "*" "Done!"

    box_end
}

########################################################################
# setup_ngrok
########################################################################

setup_ngrok() {

    setup_service "ngrok"

}

########################################################################
# setup_ngrok
########################################################################

setup_lab() {

    setup_service "lab"

}

########################################################################
# not_implemented
########################################################################

not_implemented() {
    box_start "NOT IMPLEMENTED" 31 >&2
    box_row 40 33 "Sorry! This has not been implemented yet." >&2
    box_end >&2
    show_help >&2
    exit 1
}

########################################################################
# main
########################################################################

main() {

    if [ "$#" -le "1" ] ; then
        case "$1" in
            help|'') show_help; exit ;;
            dotfiles) setup_dotfiles; exit ;;
            conda) setup_conda; exit ;;
            jupyter) setup_jupyter; exit ;;
            sage) setup_sage; exit ;;
            dev) setup_dev; exit ;;
            killdev) remove_dev; exit ;;
            djvu) build_djvu; exit ;;
            ngrok) setup_ngrok; exit ;;
            lab) setup_lab; exit ;;
        esac
    fi

    box_start ERROR 31 >&2
    box_row 40 33 "Usage: $0 ACTION" >&2
    box_end >&2
    show_help >&2
    exit 1

}

main "$@"
