#!/bin/bash

#exec open -a Skim "$@"

if [ $# == 0 -o "$1" == "-h" -o "$1" == "-help" ]; then
  echo "Usage: skim PDFFILE"
  exit 0
fi

file="$1"
[ "${file:0:1}" == "/" ] || file="${PWD}/${file}"

# run AppleScript
/usr/bin/osascript << EOF
  set theFile to POSIX file "$file"
  set thePath to POSIX path of (theFile as alias)
  tell application "Skim"
    activate
    open theFile
  end tell
EOF
