#!/bin/bash

complete -o default -f -X '!*.tex' vi
complete -o default -f -X '!*.+(tex|pdf|pdfd|gif|png|jpg|jpeg|svg|bmp)' view
complete -o default -f -X '!*.+(pdf|pdfd|app)' open
complete -o default -f -X '!*.+(pdf|pdfd)' skim
complete -o default -f -X '!*.+(pdf|pdfd)' acrobat

function _cenv_compl_aux() {(
    shopt -s nullglob
    ENVS_DIR=~/opt/miniconda3/envs
    if [ -d "$ENVS_DIR" ]; then
        cd "$ENVS_DIR"
        for DIR in *; do
            if [ "$DIR" != "env0" ]; then
                echo "${DIR##*-}"
            fi
        done
    fi
)}

function _cenv_compl() {
    local CENV_ARGS=(
        -init
        -create
        -remove
        -deactivate
        -usage
        -help
    )
    COMPREPLY=(
        $(compgen \
            -W \
            "$(_cenv_compl_aux) ${CENV_ARGS[*]}" \
            -- \
            "${COMP_WORDS[1]}" \
        )
    )

}

complete -F _cenv_compl cenv
complete -F _cenv_compl act
complete -F _cenv_compl activate

# vi: ft=bash
