name: env-dev-qpageview
channels:
  - conda-forge
  - default
dependencies:
  # basic deps
  - autoconf
  - automake
  - bash
  - bash-completion
  - bison
  - c-compiler
  - cmake
  - coreutils
  - ctags
  - curl
  - findutils
  - flex
  - gawk
  - git
  - git-subrepo
  - htop
  - hunspell
  - hunspell-en
  - imagemagick
  - ipython
  - libtool
  - make
  - nodejs
  - pip
  - python
  - requests
  - tar
  - tmux=3.1
  - tree
  - vim
  - wget
  - which
  # project deps
  - poppler
  - poppler-qt
  - pyinstaller
  - pyqt
  - pip:
    - qpageview
    - python-poppler-qt5
